In [1]:
import dpilqr as dec
import matplotlib.pyplot as plt
import numpy as np
import rospy
import tf
from dpilqr import plot_solve, split_agents
from distributed_mpc import *
from centralized_mpc import *
import pycrazyswarm as crazy


In [24]:
X = np.random.rand(1,18)

In [25]:
X.shape

(1, 18)

In [28]:
X

array([[0.155, 0.01 , 0.617, 0.412, 0.675, 0.282, 0.185, 0.444, 0.766,
        0.684, 0.354, 0.715, 0.226, 0.407, 0.972, 0.65 , 0.679, 0.112]])

In [26]:
X_full = np.random.rand(6,18)

In [27]:
X_full

array([[0.577, 0.908, 0.493, 0.072, 0.764, 0.948, 0.502, 0.531, 0.323,
        0.198, 0.195, 0.805, 0.877, 0.347, 0.483, 0.097, 0.636, 0.721],
       [0.332, 0.323, 0.224, 0.505, 0.649, 0.635, 0.647, 0.346, 0.052,
        0.394, 0.911, 0.594, 0.949, 0.857, 0.929, 0.998, 0.336, 0.682],
       [0.957, 0.423, 0.355, 0.259, 0.314, 0.381, 0.845, 0.217, 0.739,
        0.474, 0.581, 0.265, 0.77 , 0.532, 0.458, 0.54 , 0.365, 0.23 ],
       [0.336, 0.864, 0.482, 0.437, 0.951, 0.17 , 0.351, 0.99 , 0.13 ,
        0.293, 0.226, 0.956, 0.72 , 0.227, 0.405, 0.872, 0.389, 0.921],
       [0.335, 0.923, 0.519, 0.201, 0.927, 0.29 , 0.824, 0.401, 0.474,
        0.571, 0.044, 0.817, 0.428, 0.663, 0.006, 0.023, 0.63 , 0.978],
       [0.21 , 0.435, 0.974, 0.315, 0.245, 0.223, 0.296, 0.439, 0.199,
        0.776, 0.092, 0.629, 0.854, 0.319, 0.748, 0.031, 0.713, 0.228]])

In [31]:
X_full[5]

array([0.21 , 0.435, 0.974, 0.315, 0.245, 0.223, 0.296, 0.439, 0.199,
       0.776, 0.092, 0.629, 0.854, 0.319, 0.748, 0.031, 0.713, 0.228])

In [29]:
X = np.r_[X, np.tile(X_full[5], (0, 1))]

In [30]:
X

array([[0.155, 0.01 , 0.617, 0.412, 0.675, 0.282, 0.185, 0.444, 0.766,
        0.684, 0.354, 0.715, 0.226, 0.407, 0.972, 0.65 , 0.679, 0.112]])

In [16]:
X.shape

(2, 18)

In [3]:
start_pos_drone1 = [0.5, 1.5, 1]
start_pos_drone2 = [2.5, 1.5, 1]
start_pos_drone3 = [1.5, 1.3, 1]

goal_pos_drone1 = [2.5, 1.5, 1]
goal_pos_drone2 = [0.5, 1.5, 1]
goal_pos_drone3 = [1.5, 2.2, 1]

start_pos_list = [start_pos_drone1, start_pos_drone2, start_pos_drone3]
goal_pos_list = [goal_pos_drone1, goal_pos_drone2 , goal_pos_drone3]

In [5]:
n_agents=3

In [6]:
u_ref = np.tile(u_ref_base,n_agents)

In [7]:
u_ref.shape

(9,)

In [8]:
x = np.hstack([start_pos_list,np.zeros((n_agents,3))]).flatten() 

In [25]:
x_goal = np.hstack([goal_pos_list,np.zeros((n_agents,3))]).flatten().reshape(-1,1)

In [26]:
x.shape

(18,)

In [27]:
x_goal.shape

(18, 1)

In [28]:
xi = x.reshape(-1, 1)

In [29]:
xi.shape

(18, 1)

In [32]:
np.all(dec.distance_to_goal(xi,x_goal,n_agents,n_states,3) <= )

False