In [13]:
import dpilqr as dec
import matplotlib.pyplot as plt
import numpy as np
import rospy
import tf
from dpilqr import plot_solve, split_agents
from distributed_mpc import *
from centralized_mpc import *
import pycrazyswarm as crazy
import util


In [23]:
theta_max = np.pi / 3
phi_max = np.pi / 3

v_max = 5
v_min = -5

theta_min = -np.pi /3
phi_min = -np.pi / 3

tau_max = 20
tau_min = 0

x_min = -5
x_max = 5

y_min = -5
y_max = 5

z_min = 0
z_max = 4.0

a_max = 3.0
a_min = -3.0

# u_ref_base = np.array([0,0,g])
u_ref_base = np.array([0,0,0,0,0,0])

# max_input_base = np.array([[theta_max], [phi_max], [tau_max]])
# min_input_base = np.array([[theta_min], [phi_min], [tau_min]])
max_input_base = np.array([[v_max], [v_max], [v_max], [a_max],[a_max], [a_max]])
min_input_base = np.array([[v_min], [v_min], [v_min], [a_min],[a_min], [a_min]])

max_state_base = np.array([[x_max], [y_max], [z_max], [v_max],[v_max], [v_max]])
min_state_base = np.array([[x_min], [y_min], [z_min], [v_min],[v_min], [v_min]])

n_states = 6
n_inputs = 6

In [36]:
n_agents = 3
n_states = 6
n_controls = 6
n_dims = [3] * n_agents
x_dims = [n_states] * n_agents

Q = np.eye(n_states*n_agents) * 100
R = np.eye(n_inputs*n_agents) * 0.01

Qf = 1000.0 * np.eye(Q.shape[0])


max_input = np.tile(max_input_base,n_agents)
min_input = np.tile(min_input_base,n_agents)
max_state = np.tile(max_state_base,n_agents)
min_state = np.tile(min_state_base,n_agents)

In [75]:
max_input.T.flatten().shape

(18,)

In [77]:
U_try = np.random.rand(18,10)

In [79]:
for k in range(10): #loop over control intervals
    
    #Constraints on inputs:
    for j in range(max_input.T.flatten().shape[0]):
        # print(U[j,k].shape,max_input[j].shape)
        # print(j,k)
        print(U_try[j,k],)


0.6066058900429724
0.566989075659338
0.01737085639837721
0.5389921903737451
0.6549264708502558
0.09625559400981876
0.05992490102141934
0.1485328557015042
0.9615158531521806
0.42927817614440955
0.9053448182107106
0.5188380077989796
0.2795687551980238
0.5595334916942033
0.29757276576846314
0.8083221944252473
0.7444394532997889
0.4392139417323305
0.21941431716392423
0.5822770992770286
0.7192825857561279
0.018148986016864432
0.1517461548380511
0.164096269482487
0.9077069242084926
0.01519042096760781
0.23998691695604502
0.4621486861627728
0.7457397080094276
0.9766337186849481
0.4129323850816221
0.7176644390566767
0.05010976773186815
0.13334551463035715
0.8246932598295539
0.9340735153381398
0.5582679286961344
0.8703611829197655
0.5542364995535471
0.24740633259288358
0.4455929771124728
0.8040997045951809
0.0580082823156276
0.43035145410073616
0.04079850458709533
0.6151203246557612
0.5808228478894264
0.4610477782514353
0.20341557140907474
0.9514252207774033
0.11216831225842827
0.85364487221106

In [31]:
X_try = np.random.rand(18,16)

In [59]:
X_try.shape

(18, 16)

In [71]:
X_try[:,0].shape

(18,)

In [73]:
max_state.T.flatten().shape[0]

18

In [63]:
max_state

array([[5., 5., 5.],
       [5., 5., 5.],
       [4., 4., 4.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [35]:
X_try[0].shape

(16,)

In [57]:
N = 10
for k in range(N+1):
    # distances = compute_pairwise_distance_Sym(X[:,k], x_dims)

        
    #constraints on states:
    for m in range(max_state.shape[0]):

        print(k,m)

0 0
0 1
0 2
0 3
0 4
0 5
1 0
1 1
1 2
1 3
1 4
1 5
2 0
2 1
2 2
2 3
2 4
2 5
3 0
3 1
3 2
3 3
3 4
3 5
4 0
4 1
4 2
4 3
4 4
4 5
5 0
5 1
5 2
5 3
5 4
5 5
6 0
6 1
6 2
6 3
6 4
6 5
7 0
7 1
7 2
7 3
7 4
7 5
8 0
8 1
8 2
8 3
8 4
8 5
9 0
9 1
9 2
9 3
9 4
9 5
10 0
10 1
10 2
10 3
10 4
10 5


In [55]:
max_state.shape[0]

6

In [47]:
for m in range(max_state.flatten().shape[0]):
    print(m)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [29]:
max_state[1]

array([5., 5., 5.])

In [25]:
u_ref = np.tile(u_ref_base,n_agents)

In [14]:
x0 = np.random.rand(18,1)

In [21]:
ids = [i for i in range(3)]

In [22]:
util.define_inter_graph_threshold(x0,0.5,[6,6,6],ids)

determining interaction graph with the following pair-wise distance : [[0.666 0.547 0.6  ]]


{0: [0, 1, 2], 1: [0, 1, 2], 2: [0, 1, 2]}

In [5]:
X = np.random.rand(1,18)

In [6]:
X

array([[0.329, 0.75 , 0.786, 0.979, 0.793, 0.99 , 0.78 , 0.965, 0.853,
        0.732, 0.552, 0.508, 0.534, 0.903, 0.245, 0.229, 0.062, 0.356]])

In [7]:
np.tile(X,(1,1))

array([[0.329, 0.75 , 0.786, 0.979, 0.793, 0.99 , 0.78 , 0.965, 0.853,
        0.732, 0.552, 0.508, 0.534, 0.903, 0.245, 0.229, 0.062, 0.356]])

In [8]:
X = np.r_[X,X]

In [25]:
X.shape

(1, 18)

In [28]:
X

array([[0.155, 0.01 , 0.617, 0.412, 0.675, 0.282, 0.185, 0.444, 0.766,
        0.684, 0.354, 0.715, 0.226, 0.407, 0.972, 0.65 , 0.679, 0.112]])

In [26]:
X_full = np.random.rand(6,18)

In [27]:
X_full

array([[0.577, 0.908, 0.493, 0.072, 0.764, 0.948, 0.502, 0.531, 0.323,
        0.198, 0.195, 0.805, 0.877, 0.347, 0.483, 0.097, 0.636, 0.721],
       [0.332, 0.323, 0.224, 0.505, 0.649, 0.635, 0.647, 0.346, 0.052,
        0.394, 0.911, 0.594, 0.949, 0.857, 0.929, 0.998, 0.336, 0.682],
       [0.957, 0.423, 0.355, 0.259, 0.314, 0.381, 0.845, 0.217, 0.739,
        0.474, 0.581, 0.265, 0.77 , 0.532, 0.458, 0.54 , 0.365, 0.23 ],
       [0.336, 0.864, 0.482, 0.437, 0.951, 0.17 , 0.351, 0.99 , 0.13 ,
        0.293, 0.226, 0.956, 0.72 , 0.227, 0.405, 0.872, 0.389, 0.921],
       [0.335, 0.923, 0.519, 0.201, 0.927, 0.29 , 0.824, 0.401, 0.474,
        0.571, 0.044, 0.817, 0.428, 0.663, 0.006, 0.023, 0.63 , 0.978],
       [0.21 , 0.435, 0.974, 0.315, 0.245, 0.223, 0.296, 0.439, 0.199,
        0.776, 0.092, 0.629, 0.854, 0.319, 0.748, 0.031, 0.713, 0.228]])

In [31]:
X_full[5]

array([0.21 , 0.435, 0.974, 0.315, 0.245, 0.223, 0.296, 0.439, 0.199,
       0.776, 0.092, 0.629, 0.854, 0.319, 0.748, 0.031, 0.713, 0.228])

In [29]:
X = np.r_[X, np.tile(X_full[5], (0, 1))]

In [30]:
X

array([[0.155, 0.01 , 0.617, 0.412, 0.675, 0.282, 0.185, 0.444, 0.766,
        0.684, 0.354, 0.715, 0.226, 0.407, 0.972, 0.65 , 0.679, 0.112]])

In [16]:
X.shape

(2, 18)

In [3]:
start_pos_drone1 = [0.5, 1.5, 1]
start_pos_drone2 = [2.5, 1.5, 1]
start_pos_drone3 = [1.5, 1.3, 1]

goal_pos_drone1 = [2.5, 1.5, 1]
goal_pos_drone2 = [0.5, 1.5, 1]
goal_pos_drone3 = [1.5, 2.2, 1]

start_pos_list = [start_pos_drone1, start_pos_drone2, start_pos_drone3]
goal_pos_list = [goal_pos_drone1, goal_pos_drone2 , goal_pos_drone3]

In [5]:
n_agents=3

In [6]:
u_ref = np.tile(u_ref_base,n_agents)

In [7]:
u_ref.shape

(9,)

In [8]:
x = np.hstack([start_pos_list,np.zeros((n_agents,3))]).flatten() 

In [25]:
x_goal = np.hstack([goal_pos_list,np.zeros((n_agents,3))]).flatten().reshape(-1,1)

In [26]:
x.shape

(18,)

In [27]:
x_goal.shape

(18, 1)

In [28]:
xi = x.reshape(-1, 1)

In [29]:
xi.shape

(18, 1)

In [32]:
np.all(dec.distance_to_goal(xi,x_goal,n_agents,n_states,3) <= )

False